import json
import schemas
import asyncio
import os
from typing import List
from langchain_openai import ChatOpenAI

import models
from cv_parser import parse_using_pymupdf, LangChainResumeParser
from interview_gen import InterviewOrchestrator, InterviewPlan, StageGeneration
from settings import settings


def mock_ai_generation_engine(session: models.Session) -> list[schemas.StageBase]:
    """
    Simulates AI pipeline parsing user metadata to cook up a tailored roadmap.
    """
    # Sample mock questions dataset that would normally be generated by an LLM
    behavioral_qa = [
        {
            "question": "Tell me about a time you handled a conflict in a team.",
            "expected_behavior": "STAR method, structural empathy",
        },
        {
            "question": "Why do you want to join our company?",
            "expected_behavior": "Alignment with company culture and mission",
        },
    ]

    technical_qa = [
        {
            "question": "How do you optimize an endpoint experiencing high database latency?",
            "expected_behavior": "Mentions indexing, caching, connection pooling",
        },
        {
            "question": "Explain the difference between a SQL and NoSQL database.",
            "expected_behavior": "ACID compliance vs horizontal scalability scaling traits",
        },
    ]

    return [
        schemas.StageBase(
            stage_order=1,
            stage_name="Behavioral Alignment",
            stage_description=f"Assessing cultural fit and soft skills for roles matching: {session.job_description[:30]}...",
            interviewer_persona="A warm but deeply analytical HR Manager who values team cohesion and growth mindset.",
            questions_and_answers=json.dumps(behavioral_qa),
        ),
        schemas.StageBase(
            stage_order=2,
            stage_name="Technical Core Evaluation",
            stage_description=f"Deep dive into software engineering foundations targeted for {session.company_info[:30]}...",
            interviewer_persona="A pragmatic, senior tech lead who dislikes buzzwords and values clean architecture and system safety.",
            questions_and_answers=json.dumps(technical_qa),
        ),
    ]


async def create_interview_session_service(
    session: models.Session,
) -> List[schemas.StageBase]:
    # 1. Instantiate basic LangChain OpenAI model wrappers.
    base_llm = ChatOpenAI(
            base_url=settings.BASE_URL_INTERVIEW_GEN,
            model=settings.MODEL_INTERVIEW_GEN,
            temperature=0.2,
            api_key=settings.GITHUB_TOKEN_INTERVIEW_GEN,
        ) 

    # 2. Bind structured output formats natively using LangChain
    planner_llm = base_llm.with_structured_output(InterviewPlan)
    stage_llm = base_llm.with_structured_output(StageGeneration)

    # 3. Supply to the Orchestrator
    orchestrator = InterviewOrchestrator(planner_llm=planner_llm, stage_llm=stage_llm)

    # cv_content = parse_using_pymupdf(session.cv_file_path)
    
    parser = LangChainResumeParser()
    cv_content = parser.parse(session.cv_file_path)
    
    jd = session.job_description

    company_description = session.company_info
    additional_info = session.additional_info

    # 4. Trigger Orchestration Pipeline
    pipeline_result = await orchestrator.run_pipeline(
        cv_text=cv_content,
        jd_text=jd,
        company_info=company_description,
        additional_notes=additional_info,
    )

    return pipeline_result
