import json
import schemas


def mock_ai_generation_engine(job_description: str, company_info: str) -> list[schemas.StageBase]:
    """
    Simulates AI pipeline parsing user metadata to cook up a tailored roadmap.
    """
    # Sample mock questions dataset that would normally be generated by an LLM
    behavioral_qa = [
        {"question": "Tell me about a time you handled a conflict in a team.", "expected_behavior": "STAR method, structural empathy"},
        {"question": "Why do you want to join our company?", "expected_behavior": "Alignment with company culture and mission"}
    ]
    
    technical_qa = [
        {"question": "How do you optimize an endpoint experiencing high database latency?", "expected_behavior": "Mentions indexing, caching, connection pooling"},
        {"question": "Explain the difference between a SQL and NoSQL database.", "expected_behavior": "ACID compliance vs horizontal scalability scaling traits"}
    ]

    return [
        schemas.StageBase(
            stage_order=1,
            stage_name="Behavioral Alignment",
            stage_description=f"Assessing cultural fit and soft skills for roles matching: {job_description[:30]}...",
            interviewer_persona="A warm but deeply analytical HR Manager who values team cohesion and growth mindset.",
            questions_and_answers=json.dumps(behavioral_qa)
        ),
        schemas.StageBase(
            stage_order=2,
            stage_name="Technical Core Evaluation",
            stage_description=f"Deep dive into software engineering foundations targeted for {company_info[:30]}...",
            interviewer_persona="A pragmatic, senior tech lead who dislikes buzzwords and values clean architecture and system safety.",
            questions_and_answers=json.dumps(technical_qa)
        )
    ]